services:
  server:
    platform: linux/amd64 
    restart: always 
    build:
      context: .
    image: rcastriotta/326-final
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
    env_file:
      - .env